server:
  port: 9012
spring:
  application:
    name: micro-db-pedido

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcRepositoriesAutoConfiguration